server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: easylogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: easy-log-server
          __path__: /logs/*.json
    pipeline_stages:
      - json:
          expressions:
            TimeStamp: TimeStamp
            BackupName: BackupName
            SourcePath: SourcePath
            TargetPath: TargetPath
            FileSize: FileSize
            TransferTimeMs: TransferTimeMs
            EncryptionTimeMs: EncryptionTimeMs
            MachineName: MachineName
            UserName: UserName
      - labels:
          BackupName:
          MachineName:
          UserName: